### ISSUE TITLE
Test run fails even though all tests pass

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/clojure-test-runner#20]
I was working on the `tracks-on-tracks-on-tracks` exercise and created the following implementation:

```clojure
(ns tracks-on-tracks-on-tracks)

(defn new-list []
  '())

(defn add-language [lang lang-list]
  (conj lang lang-list))

(defn first-language [lang-list]
  (first lang-list))

(defn remove-language [lang-list]
  (rest lang-list))

(defn count-languages [lang-list]
  (count lang-list))

(defn learning-list []
  (->>
    (new-list)
    (add-language "Clojure")
    (add-language "Lisp")
    (remove-language)
    (add-language "Java")
    (add-language "JavaScript")
    (count-languages)))
```

Running the tests gives me a weird result, where all tests pass but there was still an error:

![image](https://user-images.githubusercontent.com/135246/132476302-603ae281-c5d9-4884-953c-8a6580303842.png)

**Comment by angelikatyborska** [comment]
Roelof Wobben reports the same problem on Slack for lasagna, but copy-pasting the exemplar works correctly.

![afbeelding](https://user-images.githubusercontent.com/7852553/132550636-3076192e-eef2-417e-a779-d2be654b5c13.png)
![Screenshot 2021-09-08 at 18-44-16 Exercism](https://user-images.githubusercontent.com/7852553/132550693-b81cd001-e215-4f3e-9925-7190f55d85fa.png)

**Comment by RoelofWobben** [comment]
Found a clue. 
I did make a syntax error because I did `(prep-time(num-layers)) ` 
But on some way the error is not found and the tests were green

**Comment by porkostomus** [comment]
I think what is happening is I'm not properly handling the condition when there is an error in a test which _does not_ cause the entire run to error.
