### ISSUE TITLE
Errors in tests are not reported

### ISSUE THREAD

**Issue by miridius** [exercism/clojure-test-runner#41]
If any unexpected runtime errors is thrown while executing a test, it is not being reported correctly right now. There are two scenarios:

1. If the test only has one assertion, then the test is reported as failed but with no message.

This makes it hard to figure out what went wrong. In Clojure it's quite easy (especially as a learner) to have some accidental runtime errors e.g. passing an odd number of forms to `(cond)` because they forgot to put `:else` before the last form. Whenever this happened to me I would have to copy paste my whole code into a clojure repl on my machine and then try running the code from the tests to see the error.

To reproduce this, use the following code in the Hello World exercise:

```clojure
(ns hello-world)

(defn hello []
  (assert false))
```

2. If the test has multiple assertions and one or more of them throws an exception, then:
   1. the test is reported as passed if *any* of the other assertions pass, or failed (without message like in the first scenario) if all either failed or errored.
   2. Even if it is reported as passed, the overall status is still failed
   3. If it is reported as passed, it won't increase the overall test failure count.

So the user will often see "0 tests failed" in red, and all tests show green, but then they can't submit and are told to first make all tests pass.

To reproduce this, use this solution for the Go Counting exercise (designed to pass the at least one assertion of each test but throw exceptions for some other assertions):

```clojure
(ns go-counting)

;; passes the last 4 assertions, throws on the first 4
(defn territory [grid [x y]]
  (assert false)) 

;; passes the first assertion, throws on the others
(defn territories [grid]
  (assert (= grid [" "]))
  {:black-territory #{} :white-territory #{} :null-territory  #{[0 0]}})
```

I believe the cause for both issues is a combination of the following things in `test-runner.clj`
1. [line 84](https://github.com/exercism/clojure-test-runner/blob/main/test-runner.clj#L84) - unlike for pass and fail, in case of errors only the name is saved and not the message. Not sure if we want to use the `:message` directly from clojure.test or craft our own? It might be helpful to include the line number as well (clojure.test provides this with key `:line`)
2. unlike pass/fail, the errors atom just stores a vector of strings instead of a vector of maps, but on [line 106](https://github.com/exercism/clojure-test-runner/blob/main/test-runner.clj#L106) it is being treated as a map (trying to access the `:name` key). This would be fixed by changing line 84 to use a map, but we must be careful to update line 104 as well to be like the fail/pass cases.
3. It seems that when a test has multiple assertions, clojure.test calls `report` multiple times, once for each assertion, which means that the same test name will appear in more than one of the test results atoms. This is a bigger issue that maybe should have its own ticket, because if some assertions pass and others fail the test is shown is passing but the overall result is fail.

**Comment by miridius** [comment]
After some experimenting, clojure.test does not provide a `:message` on errors but it provides the throwable itself as the `:actual`. `:line` number and stack trace are useless unfortunately as it's all babashka/clojure internals. But calling `str` on the throwable gives a nice one line summary.

**Comment by BTowersCoding** [comment]
Wow, thank you so much for this :)

This is the first real feedback we've gotten since I hacked this together last year, without much experience or guidance. I've been very interested in having it reviewed by someone who could identify aspects that could be clarified or suggest an alternative approach.

Excited to explore the linked PR.

**Comment by miridius** [comment]
Haha cool 😃  You've done really great service here and I greatly enjoyed going through all the Clojure exercises via the web editor, so I'm more than happy to give back!

**Comment by miridius** [comment]
Yup it's working! 🥳🥳🥳 

![image](https://user-images.githubusercontent.com/44704707/179086788-7a0322f5-f059-4150-ade6-2446b2e7abde.png)

![image](https://user-images.githubusercontent.com/44704707/179087791-89825b1d-e8c1-4be6-976b-ca17e5687c6d.png)

Looking at this in the UI now though I think the "An unexpected error occurred:" text is redundant. I didn't realise there would be a "TEST ERROR" heading above it already! We can clean that up another time though. When I have some time I'll make an issue listing all the things we discussed in #42 which are still open
